(* we wszystkich produkcjach oprócz complex-coord i identifier każdy przecinek*)
(* można zastąpić ', ws, ', jeżeli chcemy uwzględnić gdize mogą, ale nie muszą*)
(* być białe znaki *)

ws = {mws}
mws = ("	" | "
"| " "), {mws}

(* EXPRESSIONS *)
complex-coord = ["+" | "-"], digit, {digit}, [".", {digit}]
const = digit, {digit}, [".", {digit}] | "(", complex-coord, ",", complex-coord, ")" | "true" | "false" | '"', { char }, '"'
expr = const | identifier, mws, "[", [expr, [(":" | ".."), expr]], "]" | identifier, "(", [expr, {",", expr}], ")" | "(", expr, ")" | "#", expr | expr, "^", expr, | "-", expr, | expr, ("*" | "/"), expr, | expr, mws, "mod", mws, expr | expr, ("+"|"-"|"&"), expr | expr, ("==" | "!=" | "<" | "<=" | ">" | ">="), expr | "not", mws, expr | expr, mws, "and", mws, expr | expr, mws, ("or" | "xor"), mws, expr

(* STATEMENTS *)
block = "{", stmt, {stmt, }, "}"
option = letter, {letter | "-"}
stmt = ["!"], identifier, "(", [expr, {",", expr}], ")", ";" | identifier, "=", expr, ";" | expr, ("->" | "<-" | "<->"), expr, ";" | "for", mws, identifier, "=", expr, mws, "to", mws, expr, [mws, "step", mws, expr], block | "while", mws, expr, block | block, "until", mws, expr, ";" | "if", mws, expr, block, ["else", block] | "return", mws, expr, ";" | "input", [mws, expr], mws, identifier, ";" | "print", mws, expr, [",", expr], ";" | "exit", mws, [expr], ";" | "measure", mws, expr, [",", identifier], ";" | "reset", ";" | "dump", [mws, expr], ";" | "list", [mws, identifier, {",", identifier}], ";" | ("load" | "save"), [mws, expr], ";" | "shell", ";" | "set", mws, option, ["," expr], ";" | stmt, ";"

(* DEFINITIONS *)
identifier = letter, {letter}
type = "int" | "real" | "complex" | "string" | "qureg" | "quvoid" | "quconst" | "quscratch"
const-def = "const", identifier, "=", expr, ";"
var-def = type, mws, identifier, [mws, expr], ";" | type, mws, identifier, ["=", expr], ";"
arg-def = type, mws, identifier
arg-list = "(", [arg-def, {",", arg-def}], ")"
body = "{", {const-def | var-def} {stmt}, "}"
def = const-def | var-def | type, mws, identifier, arg-list, body | ("procedure" | "operator" | "qufunct"), mws, identifier, arg-list, body | "extern", mws, ("operator" | "qufunct"), mws, identifier, arg-list, ";"